name = "afri-auth-website"
compatibility_date = "2025-05-25"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "afri-auth-db"
database_id = "9ac69c02-2fa6-48a6-9e0a-e646aa68a684"

[vars]
AUTH_SECRET = "${AUTH_SECRET}"
AUTH_TRUST_HOST = "true"
GITHUB_ID = "${GITHUB_ID}"
GITHUB_SECRET = "${GITHUB_SECRET}"
