name = "afri-auth-website-workers"
compatibility_date = "2025-05-23"
main = "src/index.ts"

[[d1_databases]]
binding = "DB"
database_name = "afri-auth-db"
database_id = "9ac69c02-2fa6-48a6-9e0a-e646aa68a684"
