name: Deploy to Cloudflare

on:
  push:
    branches:
      - main

jobs:
  deploy-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js with nvm
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install 22.9.0
          nvm use 22.9.0
          npm install -g npm@10.9.2
          npm --version

      - name: Debug Directory Contents
        run: pwd && ls -la

      - name: Verify package.json and Lockfile
        run: |
          ls -la package.json || exit 1
          if [ ! -f package-lock.json ]; then
            npm install
            ls -la package-lock.json || exit 1
            cat .gitignore | grep package-lock.json && exit 1 || echo "package-lock.json not ignored"
            echo "package-lock.json generated but not committed. Please commit it via GitHub."
            exit 1
          fi
          npm install --dry-run --package-lock-only
        continue-on-error: false

      - name: Clean Install Dependencies
        run: npm ci
        continue-on-error: false

      - name: Fix Vulnerabilities
        run: npm audit fix
        continue-on-error: true

      - name: Sync SvelteKit
        run: npm run sync
        continue-on-error: false

      - name: Build
        run: npm run build
        env:
          NODE_DEBUG: '*'
        continue-on-error: false

      - name: Verify Build Output
        run: ls -la .svelte-kit/cloudflare || exit 1
        continue-on-error: false

      - name: Deploy to Cloudflare Pages
        run: npx wrangler pages deploy .svelte-kit/cloudflare --project-name=afri-auth-website --commit-dirty=true --log-level debug
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        continue-on-error: false

  deploy-workers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.9.0'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.2.14'

      - name: Debug Directory Contents
        run: pwd && ls -la

      - name: Verify package.json and Lockfile
        run: |
          ls -la package.json || exit 1
          if [ ! -f bun.lockb ]; then
            bun install
            ls -la bun.lockb || exit 1
            cat .gitignore | grep bun.lockb && exit 1 || echo "bun.lockb not ignored"
            echo "bun.lockb generated but not committed. Please commit it via GitHub."
            exit 1
          fi
          bun install --dry-run
        continue-on-error: false

      - name: Install Dependencies
        run: bun install
        continue-on-error: false

      - name: Transpile TypeScript
        run: npx tsc src/index.ts --outFile src/index.js
        continue-on-error: false

      - name: Deploy to Cloudflare Workers
        run: bunx wrangler deploy src/index.js --name=afri-auth-website --dry-run=false --log-level debug
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
          GITHUB_ID: ${{ secrets.GITHUB_ID }}
          GITHUB_SECRET: ${{ secrets.GITHUB_SECRET }}
        continue-on-error: false