name: Deploy to Cloudflare

on:
  push:
    branches:
      - main

jobs:
  deploy-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.9.0'
          cache: 'npm'

      - name: Install npm
        run: npm install -g npm@10.9.2

      - name: Debug Directory Contents
        run: pwd && ls -la

      - name: Verify package.json and Lockfile
        run: |
          ls -la package.json || exit 1
          if ! npm install --dry-run --package-lock-only; then
            rm -f package-lock.json
            npm install
          fi
        continue-on-error: false

      - name: Clean Install Dependencies
        run: npm ci
        continue-on-error: false

      - name: Fix Vulnerabilities
        run: npm audit fix
        continue-on-error: true

      - name: Sync SvelteKit
        run: npm run sync
        continue-on-error: false

      - name: Build
        run: npm run build
        continue-on-error: false
        env:
          NODE_DEBUG: '*'

      - name: Verify Build Output
        run: ls -la .svelte-kit/cloudflare || exit 1
        continue-on-error: false

      - name: Deploy to Cloudflare Pages
        run: npx wrangler pages deploy .svelte-kit/cloudflare --project-name=afri-auth-website --commit-dirty=true --log-level debug
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        continue-on-error: false

  deploy-workers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.2.14'

      - name: Debug Directory Contents
        run: pwd && ls -la

      - name: Verify package.json and Lockfile
        run: |
          ls -la package.json || exit 1
          if ! bun install --dry-run; then
            rm -f bun.lockb
            bun install
          fi
        continue-on-error: false

      - name: Install Dependencies
        run: bun install
        continue-on-error: false

      - name: Deploy to Cloudflare Workers
        run: bunx wrangler deploy src/index.ts --name=afri-auth-website --dry-run=false --log-level debug
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
          GITHUB_ID: ${{ secrets.GITHUB_ID }}
          GITHUB_SECRET: ${{ secrets.GITHUB_SECRET }}
        continue-on-error: false